#!/usr/bin/env bash
set -e
sudo apt-get remove docker docker-engine -y
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install docker-ce -y
sudo pip install docker-compose ansible
sudo gpasswd -a $USER docker
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

echo "========================================="
echo "=      Please reboot your computer      ="
echo "========================================="

