#!/usr/bin/env bash

cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) || exit 1

cd /release-manager  # going to the main directory of the project

isort \
  --check-only \
  --diff \
  --recursive \
  --settings-path main
