#!/usr/bin/env bash

cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) || exit 1

cd /release-manager  # going to the main directory of the project

prospector --profile /release-manager/main/prospector.yaml --die-on-tool-error
