# vim: ft=ansible
---

APP_IMAGE: TODO
APP_NAME: release-manager

CONTAINER_ID: "{{ lookup('env', 'CONTAINER_ID') }}"
DOCKER_REGISTRY_KEY: 'docker-registry'

HEALTHCHECK_URL: '/static/app.js'

OVERRIDE_GID: "{{ lookup('env', 'OVERRIDE_GID') }}"
OVERRIDE_UID: "{{ lookup('env', 'OVERRIDE_UID') }}"

ENV:
    ALLOWED_CIDR_NETS: "{{ APPLICATION.ALLOWED_CIDR_NETS|join(',') }}"
    ALLOWED_HOSTS: "{{ APPLICATION.ALLOWED_HOSTS|join(',') }}"
    BASIC_AUTH_PASS: "{{ APPLICATION.BASIC_AUTH_PASS }}"
    BASIC_AUTH_USER: "{{ APPLICATION.BASIC_AUTH_USER }}"
    DEBUG: "{{ APPLICATION.DEBUG|default('true') }}"
    DOCKER_TAG: "{{ lookup('env', 'DOCKER_TAG') }}"
    ENVIRONMENT: "{{ APPLICATION.ENVIRONMENT }}"
    GITLAB_HOST: "{{ APPLICATION.GITLAB_HOST }}"
    GITLAB_PRIVATE_TOKEN: "{{ APPLICATION.GITLAB_PRIVATE_TOKEN }}"
    JIRA_HOST: "{{ APPLICATION.JIRA_HOST }}"
    JIRA_PASSWORD: "{{ APPLICATION.JIRA_PASSWORD }}"
    JIRA_PROJECTS: "{{ APPLICATION.JIRA_PROJECTS|join(',') }}"
    JIRA_USERNAME: "{{ APPLICATION.JIRA_USERNAME }}"
    PROJECTS: "{{ APPLICATION.PROJECTS | from_json | to_json }}"
    ROCKET_HOOK_URL: "{{ APPLICATION.ROCKET_HOOK_URL }}"
    VERSION: "{{ lookup('env', 'GIT_HEAD') }}"

